### Spring properties
# Service registers under this name
spring:
  application:
    name: data-service
  activemq:
    broker-url: tcp://192.168.0.27:61616
    
# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://192.168.0.27:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 2222

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
    
default:
  databasename: marketdata
  hostname: 192.168.0.27
  portnumber: 27017    

queue:
  marketdata: marketdata.q