### Spring properties
# Service registers under this name
spring:
  application:
    name: data-service

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 2222

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
    
default:
  databasename: marketdata
  hostname: 127.0.0.1
  portnumber: 27017    