spring:
  activemq:
    broker-url: tcp://192.168.99.100:61616

queue:
  marketdata: marketdata.q

error:
  whitelabel:
    enabled: true
        
default:
  period: -2
  databasename: marketdata
  hostname: 192.168.99.100
  portnumber: 27017
