spring:
  activemq:
    broker-url: tcp://localhost:61616

queue:
  marketdata: marketdata.q

error:
  whitelabel:
    enabled: true
        
default:
  period: -2
  databasename: marketdata
  hostname: localhost
  portnumber: 27017
