# Configure this Discovery Server
eureka:
  instance:
    hostname: 192.168.99.100
  client: 
    registerWithEureka: false
    fetchRegistry: false
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  
# HTTP (Tomcat) port
server:
  port: 1111