### Spring properties
# Service registers under this name
spring:
  application:
    name: test-service

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://192.168.0.27:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 2226

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false
    
default:
  databasename: marketdata
  hostname: 192.168.0.27
  portnumber: 27017    